version: "3"

services:
  foundation-notebook-ewang:
    image: at-docker.ad.bcm.edu:5000/foundation:v0
    env_file: ../../environments/ewang/.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/:/mnt/
      - /mnt/lab/users/ewang/notebooks/foundation/:/notebooks/
      - /home/ewang/projects/neuro/fnn/:/src/fnn/
      - /home/ewang/projects/neuro/djutils/:/src/djutils/
      - /home/ewang/projects/neuro/foundation/:/src/foundation/
    entrypoint:
      [
        "/bin/bash",
        "-c",
        "pip install -e /src/fnn && \
         pip install -e /src/djutils && \
         pip install -e /src/foundation && \
         jupyter lab --NotebookApp.token=$${JUPYTER_TOKEN}"
      ]
    working_dir: /
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '0', '1' ]
              capabilities: [ gpu ]
