apiVersion: batch/v1
kind: Pod
metadata:
  name: foundation-jupyter
  labels:
    app: foundation-jupyter
spec:
  volumes:
    - name: scratch09
      hostPath:
        path: /mnt/scratch09
    - name: time
      hostPath:
        path: /etc/localtime
  restartPolicy: OnFailure
  hostNetwork: true
  hostIPC: true
  priorityClassName: high-priority
  containers:
    - name: run
      image: at-docker.ad.bcm.edu:5000/foundation:v0
      resources:
        limits:
          nvidia.com/gpu: 2
        requests:
          cpu: 4
          memory: "16Gi"
      volumeMounts:
        - name: scratch09
          mountPath: /mnt/scratch09
        - name: time
          mountPath: /etc/localtime:ro
      env:
        - name: DJ_SUPPORT_FILEPATH_MANAGEMENT
          value: "TRUE"
        - name: DJ_HOST
          valueFrom:
            secretKeyRef:
              name: datajoint-credentials
              key: DJ_HOST
        - name: DJ_USER
          valueFrom:
            secretKeyRef:
              name: datajoint-credentials
              key: DJ_USER
        - name: DJ_PASS
          valueFrom:
            secretKeyRef:
              name: datajoint-credentials
              key: DJ_PASS
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: github-credentials-token
              key: GITHUB_TOKEN
      command: ["/bin/bash"]
      args: [
          "-c",
          "git clone https://$(GITHUB_TOKEN)@github.com/cajal/djutils.git -b main /src/djutils \
          && pip install /src/djutils \
          && git clone https://$(GITHUB_TOKEN)@github.com/cajal/fnn.git -b main /src/fnn \
          && pip install /src/fnn \
          && git clone https://$(GITHUB_TOKEN)@github.com/cajal/foundation.git -b main /src/foundation \
          && pip install /src/foundation \
          && python3 /src/foundation/deploy/scripts/fnn.py",
        ]
  tolerations:
    - key: "gpu"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
    - key: "lab"
      operator: "Equal"
      value: "at"
      effect: "NoSchedule"
    - key: "large_gpu_memory"
      operator: "Equal"
      value: "true"
      effect: "PreferNoSchedule"
    - key: "24GB_gpu_memory"
      operator: "Equal"
      value: "true"
      effect: "PreferNoSchedule"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: gpu_mem_size
                operator: In
                values:
                  - 24GB
                  - 32GB
              - key: kubernetes.io/hostname
                operator: In
                values:
                  # - at-gpu7
                  - at-gpu10
                  - at-gpu11
                  - at-gpu12
---
apiVersion: v1
kind: Service
metadata:
  name: foundation-jupyter-service
spec:
  type: NodePort
  selector:
    app: foundation-jupyter
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
