apiVersion: batch/v1
kind: Job
metadata:
  name: foundation-recording
spec:
  parallelism: 20
  backoffLimit: 50
  template:
    spec:
      volumes:
        - name: scratch09
          hostPath:
            path: /mnt/scratch09
        - name: time
          hostPath:
            path: /etc/localtime
      restartPolicy: OnFailure
      hostNetwork: true
      hostIPC: true
      priorityClassName: medium-priority
      containers:
        - name: run
          image: at-docker.ad.bcm.edu:5000/foundation:v0
          resources:
            requests:
              cpu: 10
              memory: "16Gi"
          volumeMounts:
            - name: scratch09
              mountPath: /mnt/scratch09
            - name: time
              mountPath: /etc/localtime:ro
          env:
            - name: DJ_SUPPORT_FILEPATH_MANAGEMENT
              value: "TRUE"
            - name: DJ_HOST
              valueFrom:
                secretKeyRef:
                  name: datajoint-credentials
                  key: DJ_HOST
            - name: DJ_USER
              valueFrom:
                secretKeyRef:
                  name: datajoint-credentials
                  key: DJ_USER
            - name: DJ_PASS
              valueFrom:
                secretKeyRef:
                  name: datajoint-credentials
                  key: DJ_PASS
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: github-credentials-token
                  key: GITHUB_TOKEN
          command: ["/bin/bash"]
          args: [
              "-c",
              "git clone https://$(GITHUB_TOKEN)@github.com/cajal/djutils.git -b main /src/djutils \
              && pip install -e /src/djutils \
              && git clone https://$(GITHUB_TOKEN)@github.com/cajal/foundation.git -b main /src/foundation \
              && pip install -e /src/foundation \
              && python3 /src/foundation/deploy/scripts/recording.py",
            ]
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - at-compute002
                      - at-compute003
                      - at-compute004
                      - at-compute005
                      - at-compute006
                      - jr-compute001
